spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/switch_monitor?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
      username: root
      password: 123456
      initial-size: 20
      max-active: 200
  data:
    mongodb:
      uri: mongodb://127.0.0.1/switchmonitor

debug: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

history:
  port-saveTime: 2
  switch-saveTime: 2
  port-speed-saveTime: 2
  switch-reachable-saveTime: 2

commit:
  switchesStatusHistories-insert: 100
  switchesStatuses-update: 60
  switchesReachables-update: 50
  switchesReachableHistories-insert: 50

threshold:
  cpu: 96
  mem: 80
  temp: 60
  speed: 95

server:
  address: 0.0.0.0
  port: 8082

security:
  jwtexp: 60000000