spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/switch_monitor?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
      username: sw
      password: ENC(5HNurmobk1dlde3JU7iUtuqDGaZe96iH)
      initial-size: 20
      max-active: 200
      stat-view-servlet:
        login-username: ENC(N2i+KUyBPZJTGv55OXGQ5w==)
        login-password: ENC(sYpdQW6HInjnCeZNHzAW1w==)
  main:
    allow-bean-definition-overriding: true
  profiles:
    include: encrypt

debug: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

history:
  log-saveTime: 30
  port-saveTime: 7
  switch-saveTime: 7
  port-speed-saveTime: 7
  switch-reachable-saveTime: 7

commit:
  switchesStatusHistories-insert: 100
  switchesStatuses-update: 60
  switchesReachables-update: 50
  switchesReachableHistories-insert: 50

threshold:
  cpu: 80
  mem: 80
  temp: 60
  speed: 95
  reach: 10
  pushRecovery: 2

server:
  address: 0.0.0.0
  port: 8082

security:
  jwtDefaultExp: 60000
  jwtLoginExp: 2592000
  webLoginExp: 3000000

sync:
  port: 60000
  initInformationThread: 100

wechat:
  appid: ENC(eOr8TLUhfO8bIfuc8Vfdtbog/C2tmmZOGdZ/f6rpPAM=)
  appSecret: ENC(iqQZaIBMb3BvJzG28NPBmzIMBO5qGDar2Pwm1mKAXwnhCxfCi04SVCU2U1kPNspr)
  corpId: ENC(SyGmyVQ6KdoFkTfcdNzpqh07i81BdmQN/VibBAtu1y8=)
  debugSecret: ENC(zP0PudNLv7ay+3i7/TndZfGHXTlG9AGPfnFjS0p4pLy5qJ9EsxQv9I6RlLVJxGzv20mFcBYGulA=)
  warnSecret: ENC(CzRX4q/KiXcY7TjPZkG3fE3VQyVxtT5xaoAvKp4gLq13YAH8N71XIvEYy8w0u2rRnyQxzm69zXo=)