spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/switch_monitor?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
      username: root
      password: ENC(sYpdQW6HInjnCeZNHzAW1w==)
      initial-size: 20
      max-active: 200
  main:
    allow-bean-definition-overriding: true
  profiles:
    include: encrypt

debug: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

history:
  port-saveTime: 7
  switch-saveTime: 7
  port-speed-saveTime: 7
  switch-reachable-saveTime: 7

commit:
  switchesStatusHistories-insert: 100
  switchesStatuses-update: 60
  switchesReachables-update: 50
  switchesReachableHistories-insert: 50

threshold:
  cpu: 96
  mem: 80
  temp: 60
  speed: 95
  reach: 5
  pushRecovery: 2

server:
  address: 0.0.0.0
  port: 8082

security:
  jwtDefaultExp: 60000
  jwtLoginExp: 2592000

sync:
  port: 60000

wechat:
  appid: ENC(eOr8TLUhfO8bIfuc8Vfdtbog/C2tmmZOGdZ/f6rpPAM=)
  appSecret: ENC(iqQZaIBMb3BvJzG28NPBmzIMBO5qGDar2Pwm1mKAXwnhCxfCi04SVCU2U1kPNspr)
  corpId: ENC(SyGmyVQ6KdoFkTfcdNzpqh07i81BdmQN/VibBAtu1y8=)
  debugSecret: ENC(zP0PudNLv7ay+3i7/TndZfGHXTlG9AGPfnFjS0p4pLy5qJ9EsxQv9I6RlLVJxGzv20mFcBYGulA=)